name = "SMP Squared"
author = "Sai"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2efbcef41cec0f87abc5a34af5dea8cedb46f65cd43aa736fb6bc5e2e3e8989"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
