name = "SMP Squared"
author = "Sai"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75e707468195370f7a69ee60b6908daab66a9bf094de934d9d72d3b8c72cd366"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
