name = "SMP Squared"
author = "Sai"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82f745861e8683749d2fde4eea23f1338fe5fa6de0d85b141cc08c33221b25eb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
