#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed May 20 16:15:31 EDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.8 + EuphoriaPatches_1.9.0
