[tavern]
	#Whether the Pressing Tub drops its contents when a non-juiceable item is pressed.
	PressingTubDropContentsOnNonJuiceable = true
	#Whether to enable infinite lava from the tap. If enabled, the tap will provide infinite lava when attached to a lava cauldron.
	InfiniteLavaFromTap = true
